# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAPFSPFJbzGtWyv4OIh6VCk006mjLBUi
"""

import streamlit as st
import pandas as pd
import re
from bertopic import BERTopic
from bertopic.representation import MaximalMarginalRelevance
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
from hdbscan import HDBSCAN
from stance_analysis import run_stance_analysis

# Konfigurasi Halaman Streamlit
st.set_page_config(page_title="Analisis Tesis: Topic & Stance", layout="wide")

custom_stopwords = {
    'yg', 'ya', 'nya', 'ga', 'gak', 'udah', 'banget', 'kalo', 'sih', 'tau',
    'pas', 'gitu', 'orang', 'liat', 'buat', 'dr', 'dari', 'ke', 'di', 'dan',
    'yang', 'ini', 'itu', 'juga', 'untuk', 'dengan', 'atau', 'tapi'
}

# ==========================================
# TAHAP 1: PREPROCESSING [Sesuai Blok Diagram]
# ==========================================
def preprocess_text(text):
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    text = re.sub(r"@(\w+)", r"\1", text)
    text = re.sub(r"#(\w+)", r"\1", text)
    text = re.sub(r"[^\x00-\x7f]", " ", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    words = [word for word in text.split() if word not in custom_stopwords and len(word) > 2]
    return " ".join(words).strip()

st.title("Sistem Analisis Topik dan Sikap (Stance) Twitter")
st.markdown("Aplikasi ini disinkronkan dengan arsitektur sistem tesis: **BERTopic & IndoBERT**.")

# ==========================================
# TAHAP 2: CRAWLING DATA (Upload Dataset)
# ==========================================
uploaded_file = st.file_uploader("Unggah Dataset Twitter (CSV)", type=["csv"])

if uploaded_file is not None:
    # Membaca dataset
    df = pd.read_csv(uploaded_file)
    st.write("### Pratinjau Data Awal")
    preview_cols = ['conversation_id_str', 'full_text', 'full_text_comments']
    if 'stance' in df.columns:
        preview_cols.append('stance')
        st.info("Kolom 'stance' terdeteksi. Dataset akan menggunakan nilai 'stance' yang sudah ada.")
    st.dataframe(df[preview_cols].head())

    if st.button("Jalankan Proses Analisis"):

        # PREPROCESSING
        with st.spinner("Sedang melakukan Preprocessing teks..."):
            df['clean_post'] = df['full_text'].apply(preprocess_text)
            df['clean_comment'] = df['full_text_comments'].apply(preprocess_text)

            # Memisahkan unggahan utama untuk Topic Modeling (berdasarkan conversation_id)
            posts_df = df[['conversation_id_str', 'clean_post']].drop_duplicates(subset=['conversation_id_str']).dropna(subset=['clean_post'])
            posts_df = posts_df[posts_df['clean_post'] != ""]
            docs = posts_df['clean_post'].tolist()

        # ==========================================
        # TAHAP 3: DYNAMIC TOPIC MODELING (BERTopic)
        # ==========================================
        with st.spinner("Sedang memproses Dynamic Topic Modeling (BERTopic) pada Unggahan/Artikel..."):
            try:
                embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")
                vectorizer_model = CountVectorizer(ngram_range=(1, 2), min_df=2, max_df=0.9)
                umap_model = UMAP(
                    n_neighbors=15,
                    n_components=5,
                    min_dist=0.0,
                    metric='cosine',
                    random_state=42
                )
                hdbscan_model = HDBSCAN(
                    min_cluster_size=20,
                    metric='euclidean',
                    cluster_selection_method='eom',
                    prediction_data=True
                )
                representation_model = MaximalMarginalRelevance(diversity=0.3)

                topic_model = BERTopic(
                    embedding_model=embedding_model,
                    umap_model=umap_model,
                    hdbscan_model=hdbscan_model,
                    vectorizer_model=vectorizer_model,
                    representation_model=representation_model,
                    nr_topics="auto",
                    min_topic_size=20,
                    calculate_probabilities=True,
                )
                topics, probabilities = topic_model.fit_transform(docs)
                posts_df['Topik'] = topics

                # Mapping Topik kembali ke dataframe utama berdasarkan conversation_id_str
                topic_mapping = dict(zip(posts_df['conversation_id_str'], posts_df['Topik']))
                df['Topik'] = df['conversation_id_str'].map(topic_mapping)

            except Exception as e:
                st.error(f"Terjadi kesalahan pada Topic Modeling: {e}")


        # ==========================================
        # TAHAP 4: STANCE ANALYSIS
        # ==========================================
        with st.spinner("Sedang memproses Stance Analysis pada Komentar/Reply..."):
            try:
                df_sample = df.copy()
                df_sample['post_id'] = df_sample['conversation_id_str']
                posts_for_stance = posts_df.rename(
                    columns={
                        'conversation_id_str': 'post_id',
                        'clean_post': 'clean_text'
                    }
                )[['post_id', 'clean_text']]

                if 'stance' in df_sample.columns or 'final_stance' in df_sample.columns:
                    st.info("Menggunakan nilai stance yang sudah ada pada dataset.")
                    if 'stance_confidence' not in df_sample.columns:
                        df_sample['stance_confidence'] = 1.0
                    if 'final_stance' not in df_sample.columns and 'stance' in df_sample.columns:
                        df_sample['final_stance'] = df_sample['stance']
                else:
                    analyzed_comments = run_stance_analysis(
                        posts_df=posts_for_stance,
                        comments_df=df_sample,
                        confidence_threshold=0.45,
                        use_improved=True,
                    )
                    df_sample = analyzed_comments.copy()

                df_sample['Sikap'] = df_sample['final_stance'] if 'final_stance' in df_sample.columns else df_sample['stance']
                df_sample['Confidence'] = df_sample['stance_confidence']

            except Exception as e:
                st.error(f"Terjadi kesalahan pada Stance Analysis: {e}")

        # ==========================================
        # TAHAP 5: GABUNG TOPIK + SIKAP PER POSTINGAN
        # ==========================================
        st.success("Proses NLP Selesai!")
        st.write("### Hasil Perbaikan Stance Komentar")
        st.write("Distribusi Stance per Topik dihilangkan untuk mengurangi error. Fokus pada komentar yang sudah ada.")
        st.dataframe(
            df_sample[[
                'conversation_id_str',
                'full_text',
                'Topik',
                'full_text_comments',
                'Sikap',
                'Confidence'
            ]]
        )

        # Ringkasan jumlah stance pada komentar
        stance_counts = df_sample['Sikap'].value_counts().rename_axis('Sikap').reset_index(name='Jumlah')
        st.write("#### Ringkasan Stance Komentar")
        st.dataframe(stance_counts)
